### ISSUE TITLE
do not work with RM5

### ISSUE THREAD

**Issue by qawsed55** [yohey-i/redmine_disable_auther_notification_plugin#1]
after installing - RM fails.
Try to migrate (do not know did it need

`redmine@redmine5:~/plugins$ RAILS_ENV=production bundle exec rake redmine:plugins:migrate
(in /opt/redmine)
rake aborted!
LoadError: cannot load such file -- disable_auther_notification/issue_model_patch
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/opt/redmine/plugins/redmine_disable_auther_notification_plugin/init.rb:2:in `<top (required)>'
/opt/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/opt/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/opt/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/opt/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `catch'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:199:in `block in halting'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `each'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/reloader.rb:88:in `prepare!'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
/opt/redmine/config/environment.rb:16:in `<top (required)>'
/opt/redmine/plugins/issue_recurring/lib/tasks/issue_recurring.rake:8:in `require_relative'
/opt/redmine/plugins/issue_recurring/lib/tasks/issue_recurring.rake:8:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `block in load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/lib/tasks/redmine.rake:218:in `block in <top (required)>'
/opt/redmine/lib/tasks/redmine.rake:218:in `each'
/opt/redmine/lib/tasks/redmine.rake:218:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `block in load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.7/lib/active_support/dependencies.rb:326:in `load'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:675:in `block in run_tasks_blocks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:675:in `each'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:675:in `run_tasks_blocks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/application.rb:528:in `run_tasks_blocks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/engine.rb:464:in `load_tasks'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `public_send'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/railties-6.1.7/lib/rails/railtie.rb:207:in `method_missing'
/opt/redmine/Rakefile:7:in `<top (required)>'
/opt/redmine/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
`

**Comment by yohey-i** [comment]
@qawsed55 
I will check the issue.

**Comment by qawsed55** [comment]
it work! Thank you!
